// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRi_cYzhtN1JWAInO7go1OS9AOqyz-_N0',
    appId: '1:391387178768:web:cb60dc0519491b9ff3a795',
    messagingSenderId: '391387178768',
    projectId: 'real-time-location-track-cdea5',
    authDomain: 'real-time-location-track-cdea5.firebaseapp.com',
    storageBucket: 'real-time-location-track-cdea5.firebasestorage.app',
    measurementId: 'G-GW6KF5QJFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHnuAbTcfEMf-W5ocPZhMS3Nxv8li6pT8',
    appId: '1:391387178768:android:004a818c0fafdb2df3a795',
    messagingSenderId: '391387178768',
    projectId: 'real-time-location-track-cdea5',
    storageBucket: 'real-time-location-track-cdea5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApkLk1cSov5ZTbazl29AMo1Vx1Udixu0w',
    appId: '1:391387178768:ios:9b2526a1ef009104f3a795',
    messagingSenderId: '391387178768',
    projectId: 'real-time-location-track-cdea5',
    storageBucket: 'real-time-location-track-cdea5.firebasestorage.app',
    iosBundleId: 'com.example.realTimeLocationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApkLk1cSov5ZTbazl29AMo1Vx1Udixu0w',
    appId: '1:391387178768:ios:9b2526a1ef009104f3a795',
    messagingSenderId: '391387178768',
    projectId: 'real-time-location-track-cdea5',
    storageBucket: 'real-time-location-track-cdea5.firebasestorage.app',
    iosBundleId: 'com.example.realTimeLocationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRi_cYzhtN1JWAInO7go1OS9AOqyz-_N0',
    appId: '1:391387178768:web:df82d2a8063456c7f3a795',
    messagingSenderId: '391387178768',
    projectId: 'real-time-location-track-cdea5',
    authDomain: 'real-time-location-track-cdea5.firebaseapp.com',
    storageBucket: 'real-time-location-track-cdea5.firebasestorage.app',
    measurementId: 'G-RVSBCKRNQS',
  );
}
